services:
  - type: web
    name: lubimyczytac
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dspring.profiles.active=prod -jar target/lubimyczytac-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "21"
      # Automatyczne budowanie adresu JDBC dla Springa
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: lubimyczytac-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: lubimyczytac-db
          property: password

databases:
  - name: lubimyczytac-db
    plan: free
